version: '3.4'

services:
  catalogdb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '!QAZ2wsx@F0X'
      
    ports:
        - "3306:3306"
    volumes:
        - mysql_catalog:/var/lib/mysql 

  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=!QAZ2wsx@F0X
      - POSTGRES_DB=GameVault.BasketDb
    restart: always
    ports:
        - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/ 

  orderdb:
    container_name: orderdb
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=!QAZ2wsx@F0X
    ports:
      - "1433:1433"

  distributedcache:
    image: redis
    restart: always
    ports:
        - "6379:6379"
  
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Database=Server=catalogdb;Port=3306;Database=GameVault.CatalogDb;user=root;password=!QAZ2wsx@F0X;Allow User Variables=True
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__PostgreSqlDatabase=Host=basketdb;Port=5432;Database=GameVault.BasketDb;Username=postgres;Password=!QAZ2wsx@F0X
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSettings__DiscountUrl=http://discount.grpc:8080

    depends_on:
      - basketdb
      - distributedcache
    ports:
     - "6001:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Data Source=discountdb.db

    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
